Updated Params

diff --git a/alpine/tmux/auto-answer b/alpine/tmux/auto-answer
--- a/alpine/tmux/auto-answer
+++ b/alpine/tmux/auto-answer
@@ -1,31 +1,49 @@
 #!/bin/sh
-
+#SIP_USERNAME=$1
+if [ "${SIP_USERNAME}" == "" ]; then
+  echo "Missing CLI argument: SIP_USERNAME. Exiting"
+  exit 1
+fi
+SIP_SERVER_HOST=${SIP_SERVER_HOST:-freeswitch}
+SIP_SERVER_DOMAIN=${SIP_SERVER_DOMAIN:-$SIP_SERVER_HOST}
+SIP_PROXY_HOST=${SIP_PROXY_HOST:-$SIP_SERVER_HOST}
+SIP_SERVER_PORT=${SIP_SERVER_PORT:-5060}
+SIP_PROXY_PORT=${SIP_PROXY_PORT:-SIP_SERVER_PORT}
+SIP_PASSWORD=${SIP_PASSWORD:-freeswitch}
+# udp, tcp
+SIP_TRANSPORT=${SIP_TRANSPORT:-udp}
 # random ports in a range
-local_port=$(shuf -i 50001-55999 -n 1)
-rtp_port=$(shuf -i 56001-59999 -n 1)
+LOCAL_PORT=$(shuf -i 50001-55999 -n 1)
+RTP_PORT=$(shuf -i 56001-59999 -n 1)
 pjsua \
-  --log-level 3 \
-  --app-log-level 3 \
+  --log-level=5 \
+  --app-log-level=5 \
+  --no-stderr \
   --color \
   --light-bg \
+  --use-cli \
   --null-audio \
-  --max-calls 15 \
+  --snd-auto-close=0 \
+  --max-calls=15 \
   --no-vad \
-  --no-udp \
-  --rtcp-mux \
   --use-compact-form \
-  --reg-timeout 300 \
+  --reg-timeout=90 \
+  --rereg-delay=90 \
   --use-srtp=0 \
   --srtp-secure=0 \
-  --use-timer 1 \
+  --rtcp-mux \
+  --use-timer=1 \
   --reg-use-proxy=3 \
   --auto-update-nat=1 \
   --disable-stun \
-  --local-port ${local_port} \
-  --rtp-port ${rtp_port} \
-  --username "${REGISTER_USERNAME}" \
-  --realm "${REGISTER_DOMAIN}" \
-  --password "${REGISTER_PASSWORD}" \
-  --id "sip:${REGISTER_USERNAME}@${REGISTER_DOMAIN};transport=tcp" \
-  --contact "sip:${REGISTER_USERNAME}@${REGISTER_DOMAIN};transport=tcp" \
-  --registrar "sip:${REGISTER_DOMAIN}"
+  --local-port=${LOCAL_PORT} \
+  --rtp-port=${RTP_PORT} \
+  --realm="*" \
+  --registrar="sip:${SIP_SERVER_DOMAIN}:${SIP_SERVER_PORT};transport=${SIP_TRANSPORT}" \
+  --proxy="sip:${SIP_PROXY_HOST}:${SIP_PROXY_PORT};transport=${SIP_TRANSPORT}" \
+  --outbound="sip:${SIP_SERVER_HOST}:${SIP_SERVER_PORT};transport=${SIP_TRANSPORT}" \
+  --id="sip:${SIP_USERNAME}@${SIP_SERVER_DOMAIN}:${SIP_SERVER_PORT};transport=${SIP_TRANSPORT}" \
+  --username="${SIP_USERNAME}" \
+  --password="${SIP_PASSWORD}" \
+  --auto-answer=200 \
+  --duration=90
